### ISSUE TITLE
Ajouter une video de présentation sur la landing page

### ISSUE THREAD

**Issue by lhirlimann** [capitoledulibre/2017.capitoledulibre.org#4]
Je propose celle faite l'année dernière https://www.youtube.com/watch?v=b2Pgk1nzq9w mais j'ai aucune idée de où et comment l'intégrer sur la landing page.

**Comment by lporcheron** [comment]
Elle y était, et j'ai mis en avant l'appel à conf à la place. Je vais la remettre dans le week-end!
