### ISSUE TITLE
Make ssl better 

### ISSUE THREAD

**Issue by lhirlimann** [capitoledulibre/2017.capitoledulibre.org#5]
https://observatory.mozilla.org/analyze.html?host=2017.capitoledulibre.org get's an F :(

Where is the repo with the ssl/apache/nginx config ?

**Comment by lporcheron** [comment]
It's lighttpd... We need to update/change/improve that, you are right.

**Comment by lporcheron** [comment]
The cfp is better: https://observatory.mozilla.org/analyze.html?host=participez-2017.capitoledulibre.org

I'll see if we can improve it also

**Comment by lhirlimann** [comment]
https://mozilla.github.io/server-side-tls/ssl-config-generator/ is the first easy path

**Comment by aplufr** [comment]
Grade upgraded from :
- F to B : https://observatory.mozilla.org/analyze.html?host=2017.capitoledulibre.org 
- F to B+ : https://observatory.mozilla.org/analyze.html?host=toulibre.org
- F to B : https://observatory.mozilla.org/analyze.html?host=capitoledulibre.org
For now, Content Security Policy can't be made more secure due toulibre.org website or old cdl.org website (same conf across all website).

I don't have access to cfp to improve it.
